#!/bin/bash
#Menu
clear
echo -e " "
echo -e "========= \e[36mAuto Script By BankTK\e[0m =========="
echo -e "  "
echo -e "======= \e[31mScript Debian OS 32-64 -bit\e[0m ======="
echo -e "  "
echo -e "========= \e[32mMenu Script By BankTK\e[0m =========="
echo -e " "
echo -e "\e[33m 1 : adduser Create SSH & OpenVPN\e[0m"
echo -e "\e[34m 2 : test new  user\e[0m"
echo -e "\e[35m 3 : Change Name\e[0m"
echo -e "\e[36m 4 : Change Password,Change de logins,Change Exp\e[0m"
echo -e "\e[31m 5 : delete user SSH & OpenVPN\e[0m"
echo -e "\e[32m 6 : Auto delete user Expres\e[0m"
echo -e "\e[33m 7 : user view all member SSH & OpenVPN\e[0m"
echo -e "\e[34m 8 : restart service, OpenVPN and SSH\e[0m"
echo -e "\e[35m 9 : speedtest VPS\e[0m"
echo -e "\e[36m 10 : check TB\e[0m"
echo -e "\e[31m 11 : view user login\e[0m"
echo -e "\e[32m 12 : about this system\e[0m"
echo -e "\e[33m 13 : ban user\e[0m"
echo -e "\e[34m 14 : unban user\e[0m"
echo -e "\e[35m 15 : Install And Update File HTTP\e[0m"
echo -e "\e[36m 16 : about script auto install\e[0m"
echo -e "\e[31m 17 : Credit to http\e[0m"
echo -e "\e[32m 18 : Setup reboot time\e[0m"
echo -e "\e[33m bash 19 : backup\e[0m"
echo -e "\e[34m bash 20 : bandwidth\e[0m"
echo -e " "